### ISSUE TITLE
chassis 3D model modification

### ISSUE THREAD

**Issue by Howard2503** [TDPS-Mihotel/Mihotel#31]

**Comment by Howard2503** [comment]
- placement of RPi and STM32
- placement of sencors(if any)
- design feeding part

**Comment by LeoJhonSong** [comment]
These two designs may help you. (It seems that there are **3D models** in their github repo)

- [donkeycar](https://github.com/autorope/donkeycar)

![image](https://user-images.githubusercontent.com/37630203/76922304-44ea8b80-690b-11ea-81fe-f49f507a0b7b.png)

- [RacingRobot](https://github.com/sergionr2/RacingRobot)

![image](https://user-images.githubusercontent.com/37630203/76952850-aed55600-6948-11ea-8beb-1e3fd7180fe6.png)

**Comment by LeoJhonSong** [comment]
Just as the two examples above, I suggest  the holder you design could allow to some extent **adjustability**. For example adjust the high of camera, the angle of camera, since even we can get a reasonable configuration by simulation in SolidWorks, but the components may not reach that accuracy we thought. Therefore, to some extent adjustability could be really helpful.

**Comment by LeoJhonSong** [comment]
> * placement of RPi and STM32
> * placement of sencors(if any)
> * design feeding part
> * batteray placement

You forgot an area for the battery placement :smirk: (it could be a basket or just fix it by a few strappings)

**Comment by LeoJhonSong** [comment]
Here are some useful 3D models:
- [Raspberrypi 4B](https://grabcad.com/library/raspberry-pi-4-model-b-1)
- [Raspberrypi 3B (very beatiful)](https://grabcad.com/library/raspberry-pi-3-model-b-reference-design-solidworks-cad-raspberry-pi-raspberrypi-rpi-1)
- [Raspberry Pi Camera Module](https://grabcad.com/library/raspberry-pi-camera-4)

Also you can find more 3D models on this powerful site.
